# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vaPArBD86um5D1DwNxk_gM8P4SNNAw_j

PARTE 1 Clase Color (Encapsulamiento)
"""

class Color:
    def __init__(self, color):
        self.color = color

    @property
    def color(self):
        return self.__color

    @color.setter
    def color(self, valor):
        if not valor:
            raise ValueError("El color no puede estar vacío")
        self.__color = valor

"""PARTE 2: Clase FiguraGeometrica"""

class FiguraGeometrica:
    def __init__(self, ancho, alto):
        self.ancho = ancho
        self.alto = alto

    @property
    def ancho(self):
        return self.__ancho

    @ancho.setter
    def ancho(self, valor):
        if valor <= 0:
            raise ValueError("El ancho debe ser mayor a 0")
        self.__ancho = valor

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, valor):
        if valor <= 0:
            raise ValueError("El alto debe ser mayor a 0")
        self.__alto = valor

    def __str__(self):
        return f"Ancho: {self.ancho}, Alto: {self.alto}"

"""PARTE 3: Clase Rectangulo (Herencia múltiple)"""

class Rectangulo(FiguraGeometrica, Color):
    def __init__(self, ancho, alto, color):
        FiguraGeometrica.__init__(self, ancho, alto)
        Color.__init__(self, color)

    def area(self):
        return self.ancho * self.alto

    def perimetro(self):
        return 2 * (self.ancho + self.alto)

    def __str__(self):
        return f"Rectángulo -> {super().__str__()}, Color: {self.color}"

"""PARTE 4: Clase Cuadrado"""

class Cuadrado(Rectangulo):
    def __init__(self, lado, color):
        super().__init__(lado, lado, color)

    def __str__(self):
        return f"Cuadrado -> Lado: {self.ancho}, Color: {self.color}"

"""PARTE 5: Clase Circunferencia"""

import math

class Circunferencia(FiguraGeometrica, Color):
    def __init__(self, radio, color):
        super().__init__(radio, radio)
        Color.__init__(self, color)

    def area(self):
        return math.pi * self.ancho ** 2

    def perimetro(self):
        return 2 * math.pi * self.ancho

    def __str__(self):
        return f"Circunferencia -> Radio: {self.ancho}, Color: {self.color}"

"""PARTE 6: Prueba del programa"""

if __name__ == "__main__":
    r = Rectangulo(4, 5, "rojo")
    c = Cuadrado(3, "azul")
    circ = Circunferencia(2.5, "verde")

    print(r)
    print("Área:", r.area(), "Perímetro:", r.perimetro())

    print(c)
    print("Área:", c.area(), "Perímetro:", c.perimetro())

    print(circ)
    print("Área:", round(circ.area(), 2), "Perímetro:", round(circ.perimetro(), 2))