# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13id2yb8GSqEbg7DMV5qHxA6_jJSAIPfH
"""

class Carro:
    def __init__(self, marca, modelo, color, anio, placa):
        self.marca = marca
        self.modelo = modelo
        self.color = color
        self.anio = anio
        self.placa = placa

    def to_dict(self):
        return self.__dict__


if __name__ == "__main__":
    carro = Carro("Toyota", "Corolla", "Rojo", 2020, "ABC-123")
    print(carro.to_dict())

class FiguraGeometrica:
    def __init__(self, alto, ancho):
        self.__alto = alto      # atributo privado
        self.__ancho = ancho    # atributo privado

    # Getter para alto
    def get_alto(self):
        return self.__alto

    # Setter para alto
    def set_alto(self, alto):
        if alto > 0:
            self.__alto = alto
        else:
            print("El alto debe ser positivo")

    # Getter para ancho
    def get_ancho(self):
        return self.__ancho

    # Setter para ancho
    def set_ancho(self, ancho):
        if ancho > 0:
            self.__ancho = ancho
        else:
            print("El ancho debe ser positivo")


# Clase hija: Rectángulo
class Rectangulo(FiguraGeometrica):
    def area(self):
        return self.get_alto() * self.get_ancho()


# Clase hija: Triángulo
class Triangulo(FiguraGeometrica):
    def area(self):
        return (self.get_alto() * self.get_ancho()) / 2


# Prueba del código
rect = Rectangulo(10, 5)
print("Área del rectángulo:", rect.area())

tri = Triangulo(10, 5)
print("Área del triángulo:", tri.area())

# Usando encapsulamiento (modificando valores)
rect.set_alto(20)
print("Nuevo alto del rectángulo:", rect.get_alto())
print("Nueva área:", rect.area())

class Cliente:
    def __init__(self, nombre, apellido, cedula, email, vip,
                 direccion, telefono, celular, edad):

        self.__nombre = nombre
        self.__apellido = apellido
        self.set_cedula(cedula)
        self.__email = email
        self.__vip = vip
        self.__direccion = direccion
        self.__telefono = telefono
        self.__celular = celular
        self.set_edad(edad)

    # --- Nombre ---
    def get_nombre(self):
        return self.__nombre

    def set_nombre(self, nombre):
        self.__nombre = nombre

    # --- Apellido ---
    def get_apellido(self):
        return self.__apellido

    def set_apellido(self, apellido):
        self.__apellido = apellido

    # --- Cédula (10 dígitos) ---
    def get_cedula(self):
        return self.__cedula

    def set_cedula(self, cedula):
        if cedula.isdigit() and len(cedula) == 10:
            self.__cedula = cedula
        else:
            raise ValueError("La cédula debe tener exactamente 10 dígitos")

    # --- Email ---
    def get_email(self):
        return self.__email

    def set_email(self, email):
        if "@" in email:
            self.__email = email
        else:
            raise ValueError("Email no válido")

    # --- VIP ---
    def get_vip(self):
        return self.__vip

    def set_vip(self, vip):
        self.__vip = bool(vip)

    # --- Dirección ---
    def get_direccion(self):
        return self.__direccion

    def set_direccion(self, direccion):
        self.__direccion = direccion

    # --- Teléfono ---
    def get_telefono(self):
        return self.__telefono

    def set_telefono(self, telefono):
        self.__telefono = telefono

    # --- Celular ---
    def get_celular(self):
        return self.__celular

    def set_celular(self, celular):
        self.__celular = celular

    # --- Edad (>18) ---
    def get_edad(self):
        return self.__edad

    def set_edad(self, edad):
        if edad >= 18:
            self.__edad = edad
        else:
            raise ValueError("El cliente debe ser mayor de 18 años")

    # --- Método para mostrar datos ---
    def mostrar_info(self):
        return f"""
Nombre: {self.__nombre} {self.__apellido}
Cédula: {self.__cedula}
Email: {self.__email}
VIP: {self.__vip}
Dirección: {self.__direccion}
Teléfono: {self.__telefono}
Celular: {self.__celular}
Edad: {self.__edad}
"""


# --- Ejemplo de uso ---
try:
    cliente1 = Cliente(
        "Eli", "Perez", "1234567890", "eli@gmail.com", True,
        "Guayaquil", "042345678", "0998765432", 20
    )

    print(cliente1.mostrar_info())

    # Prueba de error
    cliente1.set_edad(16)

except ValueError as e:
    print("Error:", e)

class Cliente:
    def __init__(self, nombre, apellido, cedula, email, vip,
                 direccion, telefono, celular, edad):

        self.__nombre = nombre
        self.__apellido = apellido
        self.set_cedula(cedula)
        self.__email = email
        self.__vip = vip
        self.__direccion = direccion
        self.__telefono = telefono
        self.__celular = celular
        self.set_edad(edad)

    # --- Cédula ---
    def get_cedula(self):
        return self.__cedula

    def set_cedula(self, cedula):
        if len(cedula) == 10 and cedula.isdigit():
            self.__cedula = cedula
        else:
            print("Error: la cédula debe tener 10 dígitos")

    # --- Edad ---
    def get_edad(self):
        return self.__edad

    def set_edad(self, edad):
        if edad >= 18:
            self.__edad = edad
        else:
            print("Error: debe ser mayor de 18 años")

    # --- Mostrar datos ---
    def mostrar(self):
        print("Nombre:", self.__nombre, self.__apellido)
        print("Cédula:", self.__cedula)
        print("Email:", self.__email)
        print("VIP:", self.__vip)
        print("Dirección:", self.__direccion)
        print("Teléfono:", self.__telefono)
        print("Celular:", self.__celular)
        print("Edad:", self.__edad)


# --- Ejemplo ---
cliente1 = Cliente(
    "Eli", "Perez", "1234567890", "eli@gmail.com", True,
    "Guayaquil", "042345678", "0998765432", 20
)

cliente1.mostrar()

# probando error
cliente1.set_edad(16)